// Generated by CoffeeScript 1.6.2
var g,
  __slice = [].slice;

g = function() {
  var args, name;

  name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  if (g.attrs[name] != null) {
    if (g.attrs[name]) {
      return console.log.apply(console, ["" + name + "\t>>>\t"].concat(__slice.call(args)));
    }
  } else {
    return console.log("" + name + "\t:::\t is not implemented in log-group");
  }
};

g.attrs = {};

g.set = function(name, status) {
  return g.attrs[name] = status;
};

exports.g = g;
